name: 'csdp-report-image'
description: 'Report image to csdp'
inputs:
  CF_IMAGE:
    description: image reported, quay.io/codefresh/newly-built-image:0.0.1
    required: true
  CF_HOST:
    description: "cluster address address: https://g.codefresh.io"
    required: false
  CF_VERBOSE:
    description: "verbose output"
    required: false
  CONTAINER_REGISTRY_INTEGRATION:
    required: false
    description: list of enrichers separated by commas
  CF_ENRICHERS:
    required: false
    description: "list of integrations separated by commas: jira, github"
  CF_INSECURE:
    required: false
    description: "security flag for standard registry protocol, when set to true it enables http protocol"
  CF_WORKFLOW_URL:
    required: false
    description: "external url for the workflow"
  CF_LOGS_URL:
    required: false
    description: "external url for the logs"
  CF_GIT_BRANCH:
    required: false
    description: "The git branch to use to enrich"
  CF_GIT_SHA:
    required: false
    description: "The git SHA to use to enrich"
  CF_GIT_REPO:
    required: false
    description: "The GitHub repo to use to enrich"
  CF_GIT_INTEGRATION:
    required: false
    description: "The integration key"
  CF_JIRA_PROJECT_PREFIX:
    required: false
    description: "Jira project prefix"
  CF_JIRA_MESSAGE:
    required: false
    description: "String that contains PREFIX-ISSUE_ID"
  CF_JIRA_INTEGRATION:
    required: false
    description: "The integration key"
  CF_JIRA_FAIL_ON_NOT_FOUND:
    required: false
    description: "fail in case of ticket not found"
  CF_API_KEY:
    description: "Codefresh API KEY"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        VER=$(cat service.yaml | grep version | cut -d ':' -f 2 | tr -d ' ')
        env>cf_env
        docker run --env-file=cf_env quay.io/codefresh/csdp-report-image:$VER
