name: 'csdp-report-image'
description: 'Report image to csdp'
inputs:
  VERSION:
    description: specify client version
    required: false
    default: 0.0.62
  CF_API_KEY:
    description: "Codefresh API KEY"
    required: true
  CF_HOST:
    description: "CSDP app-proxy exposed in cluster address: https://your.clusters.ci-cd.com/app-proxy"
    required: true
  CF_VERBOSE:
    description: "verbose output"
    required: false
  CF_IMAGE:
    description: image reported, quay.io/codefresh/newly-built-image:0.0.1
    required: true
  CF_CONTAINER_REGISTRY_INTEGRATION:
    required: false
    description: "list of container integration"
  CF_DOCKERHUB_USERNAME:
    required: false
    description: "Dockerhub username"
  CF_DOCKERHUB_PASSWORD:
    required: false
    description: "Dockerhub password"
  CF_REGISTRY_USERNAME:
    required: false
    description: "Generic registry username"
  CF_REGISTRY_PASSWORD:
    required: false
    description: "Generic registry password"
  CF_REGISTRY_DOMAIN:
    required: false
    description: "Generic registry domain"
  CF_INSECURE:
    required: false
    description: "security flag for standard registry protocol, when set to true it enables http protocol"
  CF_WORKFLOW_URL:
    required: false
    description: "external url for the workflow"
  CF_LOGS_URL:
    required: false
    description: "external url for the logs"
  # Enrichers
  CF_ENRICHERS:
    required: false
    description: "list of integrations separated by commas: jira, github"
  # GIT
  CF_GIT_PROVIDER:
    required: false
    description: "Git provider"
  CF_GIT_REPO:
    required: false
    description: "The GitHub repo to use to enrich"
  CF_GIT_BRANCH:
    required: false
    description: "The git branch to use to enrich"
  CF_GIT_INTEGRATION:
    required: false
    description: "The integration key"
  ## Github
  CF_GITHUB_TOKEN:
    required: false
    description: "Github api key"
  CF_GITHUB_API_HOST_URL:
    required: false
    description: "Github api host url"
  CF_GITHUB_CONTEXT:
    required: false
    description: "Github context from Codefresh Classic platform"
  # JIRA
  CF_JIRA_API_TOKEN:
    required: false
    description: "Jira user api key"
  CF_JIRA_EMAIL:
    required: false
    description: "Jira user email"
  CF_JIRA_HOST_URL:
    required: false
    description: "Jira account host url"
  CF_JIRA_PROJECT_PREFIX:
    required: false
    description: "Jira project prefix"
  CF_JIRA_MESSAGE:
    required: false
    description: "String that contains PREFIX-ISSUE_ID"
  CF_JIRA_INTEGRATION:
    required: false
    description: "The integration key"
  CF_JIRA_FAIL_ON_NOT_FOUND:
    required: false
    description: "fail in case of ticket not found"
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        VERSION: "${{ inputs.VERSION }}"
        CF_HOST: "${{ inputs.CF_HOST }}"
        CF_API_KEY: "${{ inputs.CF_API_KEY }}"
        
        CF_IMAGE: "${{ inputs.CF_IMAGE }}"
        CF_VERBOSE: "${{ inputs.CF_VERBOSE }}"
        CF_CONTAINER_REGISTRY_INTEGRATION: "${{ inputs.CF_CONTAINER_REGISTRY_INTEGRATION }}"
        CF_DOCKERHUB_USERNAME: "${{ inputs.CF_DOCKERHUB_USERNAME }}"
        CF_DOCKERHUB_PASSWORD: "${{ inputs.CF_DOCKERHUB_PASSWORD }}"
        CF_REGISTRY_USERNAME: "${{ inputs.CF_REGISTRY_USERNAME }}"
        CF_REGISTRY_PASSWORD: "${{ inputs.CF_REGISTRY_PASSWORD }}"
        CF_REGISTRY_DOMAIN: "${{ inputs.CF_REGISTRY_DOMAIN }}"
        CF_INSECURE: "${{ inputs.CF_INSECURE }}"
        CF_WORKFLOW_URL: "${{ inputs.CF_WORKFLOW_URL }}"
        CF_LOGS_URL: "${{ inputs.CF_LOGS_URL }}"

        CF_ENRICHERS: "${{ inputs.CF_ENRICHERS }}"
        # GIT
        CF_GIT_PROVIDER: "${{ inputs.CF_GIT_PROVIDER }}"
        CF_GIT_REPO: "${{ inputs.CF_GIT_REPO }}"
        CF_GIT_BRANCH: "${{ inputs.CF_GIT_BRANCH }}"
        CF_GIT_INTEGRATION: "${{ inputs.CF_GIT_INTEGRATION }}"
        ## Github
        CF_GITHUB_TOKEN: "${{ inputs.CF_GITHUB_TOKEN }}"
        CF_GITHUB_API_HOST_URL: "${{ inputs.CF_GITHUB_API_HOST_URL }}"
        CF_GITHUB_API_PATH_PREFIX: "${{ inputs.CF_GITHUB_API_PATH_PREFIX }}"
        CF_GITHUB_CONTEXT: "${{ inputs.CF_GITHUB_CONTEXT }}"

        # JIRA
        CF_JIRA_API_TOKEN: "${{ inputs.CF_JIRA_API_TOKEN }}"
        CF_JIRA_EMAIL: "${{ inputs.CF_JIRA_EMAIL }}"
        CF_JIRA_HOST_URL: "${{ inputs.CF_JIRA_HOST_URL }}"
        CF_JIRA_PROJECT_PREFIX: "${{ inputs.CF_JIRA_PROJECT_PREFIX }}"
        CF_JIRA_MESSAGE: "${{ inputs.CF_JIRA_MESSAGE }}"
        CF_JIRA_INTEGRATION: "${{ inputs.CF_JIRA_INTEGRATION }}"
        CF_JIRA_FAIL_ON_NOT_FOUND: "${{ inputs.CF_JIRA_FAIL_ON_NOT_FOUND }}"

        # github
        CF_GITHUB_REF_NAME: "${{ github.ref_name }}"
        CF_GITHUB_COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"
        CF_GITHUB_PAYLOAD_MESSAGE: "${{ github.event.client_payload.message }}"
        CF_GITHUB_REPOSITORY: "${{ github.repository }}"


      run: |
        # add defaults
        CF_GIT_BRANCH="${CF_GIT_BRANCH:-$CF_GITHUB_REF_NAME}"
        CF_GIT_REPO="${CF_GIT_REPO:-$CF_GITHUB_REPOSITORY}"
        # built vars
        CF_WORKFLOW_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        CF_GIT_PROVIDER="${CF_GIT_PROVIDER:-github}"
        CF_CI_TYPE=github-actions
        env>cf_env
        echo "CF_CI_TYPE=$CF_CI_TYPE" >> cf_env
        echo "CF_WORKFLOW_URL=$CF_WORKFLOW_URL" >> cf_env
        echo "CF_GIT_PROVIDER=${CF_GIT_PROVIDER}" >> cf_env

        echo "CF_GIT_BRANCH $CF_GIT_BRANCH"
        echo "CF_GIT_REPO $CF_GIT_REPO"
        echo "CF_GIT_PROVIDER $CF_GIT_PROVIDER"
        docker run --env-file=cf_env "quay.io/codefresh/codefresh-report-image:$VERSION"
  
